### ISSUE TITLE
Rsnapshot clean up (rm -rf) killing drives

### ISSUE THREAD

**Issue by Slind14** [DrHyde/rsnapshot#54]
Hey,
I am already using a c3 nice level for rsync which made the backup task unnoticeable. But unfortunately as soon as the max backups are archived and the olds are being removed it is killing the hard drives. 
Is there any way to set an io nice for the remove task or other ways to optimize?

File system is already ext4

(the rm causes the system to slow down extremely for 5-10 minutes)

**Comment by bebehei** [comment]
I assume "killing the hard drive" means the harddrive has got heavy usage. Try using the option cmd_rm and ionice your rm command with that, by writing a wrapper. As this is not a code-related bug of rsnapshot, I'll close the issue. If you want to have further support checkout rsnapshot-discuss at https://lists.sourceforge.net/lists/listinfo/rsnapshot-discuss

**Comment by Slind14** [comment]
alright, thanks.
